log:
#  filename: /tmp/go-grpc.log
#  maxSize: 500
#  maxBackups: 3
#  maxAge: 3
  level: "debug"
  stdout: true
db:
  url: "axe:eecDn2@!9@tcp(192.168.0.49:9036)/ecf?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  debug : false
http:
  port: 8082
grpc:
  port: 8081
jaeger:
  serviceName: go-grpc
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1





