log:
#  filename: /tmp/go-grpc.log
#  maxSize: 500
#  maxBackups: 3
#  maxAge: 3
  level: "debug"
  stdout: true
db:
  url: "root:123456@tcp(192.168.56.10:23000)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  debug : false
http:
  port: 8082
grpc:
  port: 8081
jaeger:
  serviceName: go-grpc
  reporter:
#    localAgentHostPort: "jaeger-agent:6831"
    localAgentHostPort: "192.168.56.10:30922"
  sampler:
    type: const
    param: 1





