// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reviews.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryReviewsRequest struct {
	ProductID            uint64   `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReviewsRequest) Reset()         { *m = QueryReviewsRequest{} }
func (m *QueryReviewsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReviewsRequest) ProtoMessage()    {}
func (*QueryReviewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{0}
}

func (m *QueryReviewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReviewsRequest.Unmarshal(m, b)
}
func (m *QueryReviewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReviewsRequest.Marshal(b, m, deterministic)
}
func (m *QueryReviewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReviewsRequest.Merge(m, src)
}
func (m *QueryReviewsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryReviewsRequest.Size(m)
}
func (m *QueryReviewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReviewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReviewsRequest proto.InternalMessageInfo

func (m *QueryReviewsRequest) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

type Review struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID            uint64               `protobuf:"varint,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{1}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Review) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *Review) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Review) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

type QueryReviewsResponse struct {
	Reviews              []*Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryReviewsResponse) Reset()         { *m = QueryReviewsResponse{} }
func (m *QueryReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReviewsResponse) ProtoMessage()    {}
func (*QueryReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2a6bc9211d2c89, []int{2}
}

func (m *QueryReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReviewsResponse.Unmarshal(m, b)
}
func (m *QueryReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReviewsResponse.Marshal(b, m, deterministic)
}
func (m *QueryReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReviewsResponse.Merge(m, src)
}
func (m *QueryReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryReviewsResponse.Size(m)
}
func (m *QueryReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReviewsResponse proto.InternalMessageInfo

func (m *QueryReviewsResponse) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryReviewsRequest)(nil), "proto.QueryReviewsRequest")
	proto.RegisterType((*Review)(nil), "proto.Review")
	proto.RegisterType((*QueryReviewsResponse)(nil), "proto.QueryReviewsResponse")
}

func init() { proto.RegisterFile("reviews.proto", fileDescriptor_5b2a6bc9211d2c89) }

var fileDescriptor_5b2a6bc9211d2c89 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0xf4, 0x4f, 0x54, 0x57, 0x45, 0xc2, 0x65, 0x08, 0xa1, 0x12, 0x51, 0x16, 0x32,
	0xd0, 0x58, 0xb4, 0x2b, 0x12, 0x12, 0x62, 0x61, 0x24, 0xea, 0x04, 0x93, 0xdb, 0x5c, 0x23, 0x4b,
	0x24, 0x76, 0x6d, 0xa7, 0x15, 0x2b, 0x0f, 0xc0, 0xc2, 0xa3, 0xf1, 0x0a, 0x3c, 0x08, 0xc2, 0x76,
	0x04, 0x85, 0x4e, 0xa7, 0xf3, 0xfd, 0xbe, 0xcf, 0xfe, 0xce, 0x68, 0x24, 0x61, 0xcb, 0x60, 0xa7,
	0x32, 0x21, 0xb9, 0xe6, 0xb8, 0x67, 0x4a, 0x34, 0x29, 0x39, 0x2f, 0x9f, 0x81, 0x50, 0xc1, 0x08,
	0xad, 0x6b, 0xae, 0xa9, 0x66, 0xbc, 0x76, 0x50, 0x74, 0xee, 0xa6, 0xa6, 0x5b, 0x36, 0x6b, 0xa2,
	0x59, 0x05, 0x4a, 0xd3, 0x4a, 0x38, 0xe0, 0xd2, 0x94, 0xd5, 0xb4, 0x84, 0x7a, 0xaa, 0x76, 0xb4,
	0x2c, 0x41, 0x12, 0x2e, 0x8c, 0xc5, 0x7f, 0xbb, 0x64, 0x8e, 0xc6, 0x0f, 0x0d, 0xc8, 0x97, 0xdc,
	0xbe, 0x24, 0x87, 0x4d, 0x03, 0x4a, 0xe3, 0x09, 0x1a, 0x08, 0xc9, 0x8b, 0x66, 0xa5, 0xef, 0xef,
	0x42, 0x2f, 0xf6, 0xd2, 0x6e, 0xfe, 0x73, 0x90, 0xbc, 0x79, 0xa8, 0x6f, 0x05, 0xf8, 0x08, 0xf9,
	0xac, 0x70, 0x84, 0xcf, 0x8a, 0x7d, 0xa1, 0xff, 0x47, 0x88, 0x43, 0x14, 0x54, 0xa0, 0x14, 0x2d,
	0x21, 0xec, 0xc4, 0x5e, 0x3a, 0xc8, 0xdb, 0x16, 0x5f, 0xa3, 0xe1, 0x4a, 0x02, 0xd5, 0x50, 0x2c,
	0x58, 0x05, 0x61, 0x37, 0xf6, 0xd2, 0xe1, 0x2c, 0xca, 0x6c, 0xd8, 0xac, 0x0d, 0x9b, 0x2d, 0xda,
	0xb0, 0xf9, 0x6f, 0x3c, 0xb9, 0x41, 0x27, 0xfb, 0x29, 0x94, 0xe0, 0xb5, 0x02, 0x7c, 0x81, 0x02,
	0xb7, 0xe2, 0xd0, 0x8b, 0x3b, 0xe9, 0x70, 0x36, 0xb2, 0x56, 0x99, 0x05, 0xf3, 0x76, 0x3a, 0x5b,
	0xa3, 0xc0, 0x69, 0xf1, 0x13, 0xea, 0x19, 0x2f, 0x1c, 0x39, 0xf6, 0xc0, 0x7e, 0xa2, 0xb3, 0x83,
	0x33, 0x7b, 0x6b, 0x72, 0xfa, 0xfa, 0xf1, 0xf9, 0xee, 0x8f, 0xf1, 0x31, 0xd9, 0x5e, 0x11, 0x09,
	0x6c, 0x0b, 0x3b, 0x45, 0x36, 0xdf, 0xe4, 0x6d, 0xf0, 0x68, 0x3f, 0x79, 0xd9, 0x37, 0x65, 0xfe,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x76, 0x4b, 0xa1, 0x03, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReviewsClient is the client API for Reviews service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewsClient interface {
	Query(ctx context.Context, in *QueryReviewsRequest, opts ...grpc.CallOption) (*QueryReviewsResponse, error)
}

type reviewsClient struct {
	cc *grpc.ClientConn
}

func NewReviewsClient(cc *grpc.ClientConn) ReviewsClient {
	return &reviewsClient{cc}
}

func (c *reviewsClient) Query(ctx context.Context, in *QueryReviewsRequest, opts ...grpc.CallOption) (*QueryReviewsResponse, error) {
	out := new(QueryReviewsResponse)
	err := c.cc.Invoke(ctx, "/proto.Reviews/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewsServer is the server API for Reviews service.
type ReviewsServer interface {
	Query(context.Context, *QueryReviewsRequest) (*QueryReviewsResponse, error)
}

func RegisterReviewsServer(s *grpc.Server, srv ReviewsServer) {
	s.RegisterService(&_Reviews_serviceDesc, srv)
}

func _Reviews_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Reviews/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewsServer).Query(ctx, req.(*QueryReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reviews_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Reviews",
	HandlerType: (*ReviewsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Reviews_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reviews.proto",
}
